img_path = [
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0000.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0001.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0002.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0003.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0004.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0005.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0006.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0007.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0008.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0009.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0010.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0011.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0012.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0013.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0014.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0015.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0016.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0017.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0018.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0019.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0020.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0021.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0022.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0023.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0024.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0025.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0026.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0027.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0028.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0029.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0030.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0031.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0032.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0033.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0034.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0035.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0036.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0037.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0038.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0039.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0040.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0041.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0042.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0043.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0044.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0045.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0046.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0047.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0048.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0049.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0050.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0051.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0052.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0053.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0054.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0055.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0056.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0057.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0058.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0059.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0060.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0061.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0062.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0063.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0064.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0065.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0066.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0067.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0068.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0069.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0070.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0071.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0072.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0073.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0074.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0075.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0076.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0077.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0078.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0079.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0080.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0081.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0082.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0083.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0084.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0085.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0086.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0087.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0088.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0089.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0090.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0091.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0092.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0093.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0094.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0095.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0096.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0097.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0098.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0099.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0100.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0101.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0102.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0103.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0104.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0105.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0106.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0107.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0108.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0109.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0110.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0111.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0112.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0113.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0114.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0115.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0116.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0117.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0118.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0119.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0120.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0121.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0122.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0123.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0124.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0125.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0126.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0127.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0128.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0129.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0130.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0131.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0132.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0133.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0134.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0135.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0136.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0137.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0138.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0139.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0140.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0141.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0142.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0143.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0144.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0145.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0146.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0147.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0148.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0149.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0150.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0151.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0152.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0153.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0154.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0155.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0156.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0157.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0158.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0159.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0160.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0161.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0162.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0163.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0164.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0165.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0166.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0167.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0168.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0169.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0170.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0171.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0172.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0173.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0174.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0175.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0176.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0177.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0178.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0179.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0180.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0181.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0182.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0183.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0184.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0185.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0186.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0187.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0188.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0189.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0190.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0191.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0192.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0193.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0194.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0195.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0196.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0197.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0198.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0199.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0200.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0201.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0202.jpg',
'd:\Datasets\KAIST_All_Day\Synced_Data\small_size\KAIST_All_Day(North)\0203.jpg',
]


mat_size = length(img_path)
est_corr_mat = zeros(mat_size)

% Parameters:
clear param
param.imageSize = [256 256]; % it works also with non-square images
param.orientationsPerScale = [8 8 8 8];
param.numberBlocks = 4;
param.fc_prefilt = 4;


for i = 1:mat_size
    for j = i:mat_size
       
    img_i = imread(img_path(i,:));
    img_j = imread(img_path(j,:));
    % Computing gist requires 1) prefilter image, 2) filter image and collect
    % output energies
    [gist_i, param] = LMgist(img_i, '', param);
    [gist_j, param] = LMgist(img_j, '', param);
    
    est_corr_mat(i,j) = 1- 0.5*(norm((gist_i./norm(gist_i,1)) - (gist_j./norm(gist_j,1)),1));
    end
    i
end
save('gistdesc_KA_North.mat','est_corr_mat')

'done'

